# Site settings
title: "My Blog"
description: "Welcome to my GitHub Pages blog 🎉"
url: "https://aneesh1985-rgb.github.io"   # your GitHub Pages domain
baseurl: "/blog5"                         # repo name

# Author settings
author:
  name: "Aneesh"
  email: "your-email@example.com"

# Theme
remote_theme: alshedivat/al-folio@master

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Markdown & code highlighting
markdown: kramdown
highlighter: rouge

# Collections (optional, for publications/projects)
collections:
  publications:
    output: true
  projects:
    output: true

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - README.md
  - LICENSE
