# Site settings
title: "My Blog"
description: "Personal blog powered by al-folio"
baseurl: "/blog5"   # The subpath of your site (e.g. /blog5)
url: "https://aneesh1985-rgb.github.io"  # Your GitHub Pages URL

# Author settings
author:
  name: "Aneesh V N"
  email: "your-email@example.com"

# Build settings
markdown: kramdown
theme: al-folio

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

