title: "My Blog"
description: "Welcome to my GitHub Pages blog 🎉"
author: "Aneesh"
email: "your-email@example.com"

# IMPORTANT: set these correctly
url: "https://aneesh1985-rgb.github.io"  # your GitHub Pages domain
baseurl: "/blog5"                        # repo name

# Theme (use minima or custom one like al-folio if included in repo)
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude unnecessary files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
